services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgrest_knack_services
    ports:
      - "5432:5432"
    volumes:
      - ./init_scripts/knack_services:/docker-entrypoint-initdb.d
