version: "3"
services:
  haproxy:
    image: haproxy:2.4
    restart: always
    depends_on:
      - server-legacy-scripts
    ports:
      - "8999:80"
    volumes:
      - "./haproxy/config:/usr/local/etc/haproxy:ro"
      - "./haproxy/maps:/etc/haproxy/maps:ro"
  server-legacy-scripts:
    ports:
    - "8000:3000"
    image: postgrest/postgrest
    restart: always
    environment:
      PGRST_DB_URI: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:5432/legacy_scripts
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_JWT_SECRET: $PGRST_JWT_SECRET_LEGACY_SCRIPTS
      PGREST_MAX_ROWS: $PGREST_MAX_ROWS
